# Generated by Django 2.2.5 on 2019-12-04 20:14

from django.db import migrations, models
import shop.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_product_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('user_name', models.CharField(max_length=100)),
                ('comment', models.CharField(max_length=200)),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('order', shop.fields.OrderField(blank=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
