# Generated by Django 2.2.6 on 2019-12-05 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_product_object_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='object_id',
        ),
    ]
