# Generated by Django 2.2.5 on 2019-11-26 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20191126_2243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='address1',
            new_name='addressline1',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='address2',
            new_name='addressline2',
        ),
    ]
