# Generated by Django 2.2.5 on 2019-11-27 10:43

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('order', '0004_auto_20191127_0004'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
