# Generated by Django 2.2.5 on 2019-11-27 10:46

from django.db import migrations


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('order', '0005_auto_20191127_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('-created',), 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
