# Generated by Django 2.2.5 on 2019-11-27 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_auto_20191127_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='addressline2',
            field=models.CharField(blank=True, help_text='Appartment, suite, unit. building, floor, etc.', max_length=250, null=True),
        ),
    ]
