# Generated by Django 2.2.5 on 2019-12-03 13:25

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_auto_20191129_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='country',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressline1',
            field=models.CharField(help_text='Street address, P.O box, company name, c/o', max_length=250, null=True, verbose_name='Address Line 1'),
        ),
        migrations.AlterField(
            model_name='order',
            name='addressline2',
            field=models.CharField(blank=True, help_text='Appartment, suite, unit. building, floor, etc.', max_length=250, null=True, verbose_name='Address Line 2'),
        ),
        migrations.AlterField(
            model_name='order',
            name='city',
            field=models.CharField(max_length=250, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='Postal code'),
        ),
        migrations.AlterField(
            model_name='order',
            name='county',
            field=models.CharField(max_length=250, null=True, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='order',
            name='emailAddress',
            field=models.EmailField(blank=True, max_length=250, verbose_name='Email Address'),
        ),
    ]
