# Generated by Django 2.2.5 on 2019-12-05 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_order_paid'),
        ('order', '0012_auto_20191203_1651'),
    ]

    operations = [
    ]
