# Generated by Django 2.2.6 on 2019-12-05 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0014_auto_20191205_1513'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='username',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='username'),
        ),
    ]
